# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7bxCUtpGHCEwgT1_1m_lRL3c0rIo2t4
"""
import datetime
import os
import torch
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint

import wandb
from torch import optim, nn, utils, Tensor

import pytorch_lightning as pl
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from pytorch_lightning.loggers import WandbLogger
import glob
import pandas as pd





def make_water_data(raw, data_length, drop_columns):
    df_raw=[]
    for domain in raw:
        df=pd.read_excel("water_data.xlsx", domain + "_samples").drop_duplicates()

        qual_col = [col for col in df.columns if 'Qualifiers' in col]
        df = df.drop('Value [COND] Conductivity (umho)', axis=1)

        for col in qual_col:
            df = df[df[col].isna()].drop(col, axis=1)
        df["abs_time"] = (df.DateTime - datetime.datetime(2000, 1, 1)).dt.total_seconds() / 60
        df = df.dropna()

        cyclic_day = (df.DateTime.dt.minute + df.DateTime.dt.hour * 60) / 1440 *2*np.pi
        df['cyclic_day_sin'] = np.sin(cyclic_day)
        df['cyclic_day_cos'] = np.cos(cyclic_day)

        cyclic_year = df.DateTime.dt.dayofyear/ 365*2*np.pi
        df['cyclic_year_sin'] = np.sin(cyclic_year)
        df['cyclic_year_cos'] = np.cos(cyclic_year)

        df = df.drop('DateTime', axis=1)
        year_idx = df.columns.get_loc("abs_time")



        df_raw.append(df)

    #get normalization info
    all_domains=pd.concat(df_raw,axis=0)
    #year_idx from above
    df_features = all_domains.iloc[:, :year_idx]
    df_abs_time=all_domains.iloc[:, year_idx]

    ########################################################
    result=[]

    #variables in main


    for domain in df_raw:
        #normalize
        domain.iloc[:, :year_idx] = (domain.iloc[:, :year_idx] - df_features.mean()) / df_features.std()
        domain.iloc[:,year_idx]=(domain.iloc[:,year_idx]-df_abs_time.min())/(df_abs_time.max()-df_abs_time.min())

        temp = np.stack([domain[i:i + window_length]
                         for i in range(0, len(domain)-window_length, window_distance)])
        result.append(torch.tensor(temp).float())



    return result


    # result=[]
    # for i in range(num_domains):
    #     result.append(x[i:i+1, :, :])
    #     result.append(y[i:i+1, :, :])
    # #[(num_points, in_dim), num_points(out_dim)]
    # return result


class LinearRelu(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim), nn.ReLU()])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))
            self.net.append(nn.ReLU())

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)
class LinearElu(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim), nn.ELU()])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))
            self.net.append(nn.ELU())

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)
class Linear(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim)])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)

class SequenceModule(nn.Module):
    def __init__(self, in_dim, seq_hidden_dim, init_hidden_dim, out_dim, warmup_length):
        super().__init__()
        self.num_layers=2
        self.seq_hidden_dim=seq_hidden_dim
        self.in_dim=in_dim
        self.out_dim=out_dim
        self.warmup_length=warmup_length

        self.lstm=nn.LSTM(in_dim, hidden_size=seq_hidden_dim, num_layers=self.num_layers, proj_size=out_dim, batch_first=True)
        self.lstm_warmup=nn.LSTM(in_dim+out_dim,
                                 hidden_size=init_hidden_dim,
                                 proj_size=out_dim,
                                 num_layers=self.num_layers,
                                 batch_first=True
                                 )
    def forward(self, x):
        #batch, length, dim
        _, (h0, c0) =self.lstm_warmup(x[:, :self.warmup_length])
        return self.lstm(x[:,self.warmup_length:,:self.in_dim], (h0, c0))


class TrainInvariant(pl.LightningModule):
    def __init__(self, in_dim, f_embed_dim,  g_embed_dim, out_dim, num_domains, warmup_length):
        super().__init__()
        self.in_dim=in_dim
        self.warmup_length=warmup_length
        self.invariant=SequenceModule(in_dim, f_embed_dim, f_embed_dim, out_dim, warmup_length)
        self.train_variants=nn.ModuleList([SequenceModule(in_dim, g_embed_dim, g_embed_dim, out_dim, warmup_length) for i in range (num_domains)])
        self.test_variant=SequenceModule(in_dim, g_embed_dim, g_embed_dim, out_dim, warmup_length)
        self.num_domains=num_domains
        self.eta=lambda x,y: x+y

        self.loss=nn.MSELoss()
    def forward(self, x, domain_num):
        result_f = self.invariant(x)
        result_g =self.train_variants[domain_num](x)

        return self.eta(result_f[0], result_g[0])

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        # it is independent of forward

        losses = [self.loss(self(batch[i], i), batch[i][:, self.warmup_length:, :out_dim]) for i in
                  range(self.num_domains)]
        loss = 0
        for i in range(self.num_domains):
            loss += losses[i]
        loss = loss / len(losses)
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx) :
        losses = [self.loss(self(batch[i], i), batch[i][:, self.warmup_length:, :out_dim]) for i in
                  range(self.num_domains)]
        loss = 0
        for i in range(self.num_domains):
            loss += losses[i]
        loss = loss / len(losses)  # Logging to TensorBoard (if installed) by default
        self.log("val_loss", loss)
    # def on_fit_end(self):

    def configure_optimizers(self):
        #check if all there
        optimizer = optim.Adam(self.parameters(), lr=1e-3)

        return optimizer



def get_latest_file():
    list_of_files = glob.glob(os.path.dirname(__file__) + '/DA Thesis/**/*.ckpt',
                              recursive=True)  # * means all if need specific format then *.csv
    latest_file = max(list_of_files, key=os.path.getctime)
    return latest_file
def numpy_it(t):
    return t.detach().cpu().numpy()
if __name__=="__main__":
    # define any number of nn.Modules (or use your current ones)
    drop_columns=["Unnamed: 0", "time2.1.nsteps.",
                  "rain_t_2"]

    all_data = []
    path = "/content/drive/MyDrive/Masters/Thesis/water_data.xlsx"
    raw = [
        "Maumee",
        # "Portage",
        # "Raisin",
        # "Rock Creek",
        # "S. Turkeyfoot",
        # "Sandusky River",
        # "Wolf",

    ]

    np.random.seed(0)
    torch.use_deterministic_algorithms(True)
    torch.manual_seed(0)

    key="c20d41ecf28a9b0efa2c5acb361828d1319bc62e"


    predict_length = 102
    warmup_length=50
    window_length= predict_length + warmup_length
    f_embed_dim = 100
    g_embed_dim=50
    max_epoch=2000

    window_distance = window_length//5
    #window length / drop columnsnot used
    all_dataset = TensorDataset(*make_water_data(raw=raw, data_length=window_length, drop_columns=drop_columns))
    in_dim = 5
    out_dim = 9
    num_domains=len(raw)
    split_fraction=1
    split_point=int(len(all_dataset)*split_fraction)

    #no random
    train_dataset = all_dataset[:split_point]
    val_dataset = all_dataset[:split_point]

    #random
    train_dataset, val_dataset = torch.utils.data.random_split(all_dataset, (split_fraction,1-split_fraction))

    # train_dataset = TensorDataset(*make_quad_data_val(num_val_io_pairs, val_coef))
    # val_dataset = TensorDataset(*make_quad_data_val(num_points, val_coef))

    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_dataset,batch_size=32)
    # val_loader=train_loader
    wandb_logger=WandbLogger(project="DA Thesis", name="trash",log_model="True")
    wandb.init() ########################################################
    wandb_logger.experiment.config.update({
                                           "num_domains": num_domains,
                                           "f_embed_dim":f_embed_dim,
                                           "g_embed_dim": g_embed_dim,
                                           "max_epoch": max_epoch,
                                           "file":os.path.basename(__file__)})

    base_trans=TrainInvariant(in_dim, f_embed_dim=f_embed_dim, g_embed_dim=g_embed_dim,out_dim=out_dim,num_domains=num_domains,
                              warmup_length=warmup_length)
    #

    # base_trans = TrainInvariant.load_from_checkpoint(get_latest_file(),in_dim=in_dim, f_embed_dim=f_embed_dim,
    #                                                  g_embed_dim=g_embed_dim,
    #                                                  out_dim=out_dim,
    #                                                  num_domains=num_domains)
    # base_trans = TrainInvariant.load_from_checkpoint("epoch=1990-step=21901.ckpt",
    #                                                  in_dim=in_dim,
    #                                                  f_embed_dim=f_embed_dim,
    #                                                  g_embed_dim=g_embed_dim,
    #                                                  out_dim=out_dim,
    #                                                  num_domains=num_domains,
    #                                                  warmup_length=warmup_length
    #                                                  )


    wandb_logger.watch(base_trans, log="all")

    early_stop_callback = EarlyStopping(monitor="val_loss", min_delta=0, patience=100)
    # small_error_callback = EarlyStopping(monitor="val_loss", stopping_threshold=0.02)
    model_callback = ModelCheckpoint(
        save_top_k=1,
        monitor="train_loss",
        mode="min",

    )
    trainer1 = pl.Trainer(limit_train_batches=100,
                          logger=wandb_logger,
                          max_epochs=max_epoch,
                          # log_every_n_steps = 5,
                          accelerator="gpu", devices=1,
                          callbacks=[
                              model_callback,
                              # early_stop_callback,
                                     # small_error_callback
                                     # model_checkpoint
                                     ],
                      # fast_dev_run=True
                      )





    # trainer1.fit(base_trans, train_loader, val_loader)
    trainer1.fit(base_trans, train_loader)

    wandb.save(get_latest_file())

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir /content/drive/MyDrive/Masters/Thesis/lightning_logs --port=8008
#
# val_dataset[6]
#
# train_dataset[0]
#
# idea_module2(val_dataset[0:1][0],val_dataset[0:1][2] )

# val_dataset[0:1][1]



# Commented out IPython magic to ensure Python compatibility.
# %debug

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7bxCUtpGHCEwgT1_1m_lRL3c0rIo2t4
"""