# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7bxCUtpGHCEwgT1_1m_lRL3c0rIo2t4
"""
import copy
import os
import torch
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint

import wandb
from torch import optim, nn, utils, Tensor
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
import pytorch_lightning as pl
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from pytorch_lightning import loggers as pl_loggers
from pytorch_lightning.loggers import WandbLogger
import glob
import matplotlib.pyplot as plt
import pandas as pd





def make_water_data(raw, data_length, drop_columns):
    df_raw = [pd.read_csv(name).drop(drop_columns,1).iloc[::20, :] for name in raw]

    # df_raw = [pd.read_csv(name).loc[:,[
    #                                       # "rain_t_2",
    #                                    "s_t_2.1.nsteps.", "Ctot", "Ntot"]] for name in raw]

    all_domains=pd.concat(df_raw,axis=0)
    mean=all_domains.mean(axis=0)
    std=all_domains.std(axis=0)
    for domain in df_raw:
        normalized_domain=((domain - mean) / std).values
        return torch.tensor(normalized_domain).float()

def make_water_data2(raw, data_length, drop_columns):
    df_raw = [pd.read_csv(name).drop(drop_columns,1).iloc[::20, :] for name in raw]
    df_raw2 = [pd.read_csv(name).drop(drop_columns,1).iloc[::20, :] for name in raw2]

    # df_raw = [pd.read_csv(name).loc[:,[
    #                                       # "rain_t_2",
    #                                    "s_t_2.1.nsteps.", "Ctot", "Ntot"]] for name in raw]

    all_domains=pd.concat(df_raw2,axis=0)
    mean=all_domains.mean(axis=0)
    std=all_domains.std(axis=0)
    result=[]
    for domain in df_raw:
        normalized_domain=((domain - mean) / std).values
        return torch.tensor(normalized_domain).float()
class LinearRelu(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim), nn.ReLU()])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))
            self.net.append(nn.ReLU())

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)
class LinearElu(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim), nn.ELU()])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))
            self.net.append(nn.ELU())

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)
class Linear(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim)])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)

class SequenceModule(nn.Module):
    def __init__(self, in_dim, seq_hidden_dim, init_hidden_dim, out_dim, warmup_length):
        super().__init__()
        self.num_layers=2
        self.seq_hidden_dim=seq_hidden_dim
        self.in_dim=in_dim
        self.out_dim=out_dim
        self.warmup_length=warmup_length

        self.lstm=nn.LSTM(in_dim, hidden_size=seq_hidden_dim, num_layers=self.num_layers, proj_size=out_dim, batch_first=True)
        self.lstm_warmup=nn.LSTM(in_dim+out_dim,
                                 hidden_size=init_hidden_dim,
                                 proj_size=out_dim,
                                 num_layers=self.num_layers,
                                 batch_first=True
                                 )
    def forward(self, x):
        #batch, length, dim
        _, (h0, c0) =self.lstm_warmup(x[:, :self.warmup_length])
        return self.lstm(x[:,self.warmup_length:,:self.in_dim], (h0, c0))


class TesInvariant(pl.LightningModule):
    def __init__(self, in_dim, f_embed_dim,  g_embed_dim, out_dim, num_domains, warmup_length):
        super().__init__()
        self.in_dim=in_dim
        self.warmup_length=warmup_length
        self.invariant=SequenceModule(in_dim, f_embed_dim, f_embed_dim, out_dim, warmup_length)
        self.train_variants=nn.ModuleList([SequenceModule(in_dim, g_embed_dim, g_embed_dim, out_dim, warmup_length) for i in range (num_domains)])
        self.test_variant=SequenceModule(in_dim, g_embed_dim, g_embed_dim, out_dim, warmup_length)
        self.num_domains=num_domains
        self.eta=lambda x,y: x+y

        self.loss=nn.MSELoss()
    def forward(self, x):
        result_f = self.invariant(x)
        result_g =self.test_variant(x)

        return self.eta(result_f[0], result_g[0])

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        # it is independent of forward

        losses=[self.loss(self(batch[i], i), batch[i][:, self.warmup_length:,self.in_dim:]) for i in range (self.num_domains)]
        loss=0
        for i in range(self.num_domains):
            loss+=losses[i]
        loss=loss/len(losses)
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx) :
        losses = [self.loss(self(batch[i], i), batch[i][:, self.warmup_length:,self.in_dim:]) for i in range(self.num_domains)]
        loss = 0
        for i in range(self.num_domains):
            loss += losses[i]
        loss = loss / len(losses)        # Logging to TensorBoard (if installed) by default
        self.log("val_loss", loss)
    # def on_fit_end(self):

    def configure_optimizers(self):
        #check if all there
        optimizer = optim.Adam(self.parameters(), lr=1e-3)

        return optimizer



def get_latest_file():
    list_of_files = glob.glob(os.path.dirname(__file__) + '/DA Thesis/**/*.ckpt',
                              recursive=True)  # * means all if need specific format then *.csv
    latest_file = max(list_of_files, key=os.path.getctime)
    return latest_file
if __name__=="__main__":
    # define any number of nn.Modules (or use your current ones)
    drop_columns=["Unnamed: 0", "time2.1.nsteps.",
                  "rain_t_2"]
    all_data=[]
    # for file in os.listdir("data"):
    #     one_domain = pd.read_csv("data/"+file)
    #     one_domain=one_domain.drop("Unnamed: 0",1)
    #     all_data[file]=one_domain
    raw2 = [
        # "data/data_exportrate=0.125.csv",
        #    "data/data_exportconstrain.csv",
        # "data/data_exportsindiv30rain.csv",
        "data/data_exportCN.add=25.csv",
        "data/data_exportCN.add=40.csv",
        "data/data_exportCN.add=55.csv",
        # "data/data_exportCN.add=70.csv",
        "data/data_exportCN.add=85.csv",
        "data/data_exportCN.add=100.csv",

    ]
    raw = [
        # "data/data_exportrate=0.125.csv",
        #    "data/data_exportconstrain.csv",
        # "data/data_exportsindiv30rain.csv",
        # "data/data_exportCN.add=25.csv",
        # "data/data_exportCN.add=40.csv",
        # "data/data_exportCN.add=55.csv",
        "data/data_exportCN.add=70.csv",
        # "data/data_exportCN.add=85.csv",
        # "data/data_exportCN.add=100.csv",

    ]


    np.random.seed(0)
    torch.use_deterministic_algorithms(True)
    torch.manual_seed(0)

    key="c20d41ecf28a9b0efa2c5acb361828d1319bc62e"


    predict_length = 200
    warmup_length=100
    data_length= predict_length + warmup_length
    f_embed_dim = 1000
    g_embed_dim=100
    # f_layers=2
    # g_layers=2
    max_epoch=3

    all_dataset = TensorDataset(*make_water_data(raw=raw, data_length=data_length, drop_columns=drop_columns))
    in_dim = 1
    out_dim = 10
    num_domains=len(raw2)

    model_names=[
        [333,1670, "20 norm"],
        [518, 2595, "20 n norm"],
        [158, 318, "5 n"],
        [160, 322, "5"],
        [390, 1955, "20 n"],
        [198,995, "20"],
        [824, 14025,"n"],
        [999, 17000, ""],
    ]

    correct = make_water_data(raw, data_length, drop_columns)
    correct2 = make_water_data2(raw, data_length, drop_columns)


    for model_name in model_names:
        base_trans = TesInvariant.load_from_checkpoint(f"epoch={model_name[0]}-step={model_name[1]}.ckpt",
                                                    in_dim=in_dim,
                                                     f_embed_dim=f_embed_dim,
                                                     g_embed_dim=g_embed_dim,
                                                     out_dim=out_dim,
                                                     num_domains=num_domains,
                                                     warmup_length=warmup_length)
        correct_used=correct2 if "norm" in model_name[2] else correct
        result = copy.deepcopy(correct_used)
        result2 = copy.deepcopy(correct_used)

        for j in range(35):
            # result[100+j*200: 300+j*200, 1:]=base_trans(correct[j*200:j*200+300].reshape((1, 300, -1)))
            result[100+j*200: 300+j*200, 1:]=base_trans.invariant(correct[j*200:j*200+300].reshape((1, 300, -1)))[0]
            result2[100+j*200: 300+j*200, 1:]=base_trans.test_variant(correct[j*200:j*200+300].reshape((1, 300, -1)))[0]

        # result[100: 7300, 1:]=base_trans(correct.reshape((1, 7300, -1)), 0)
        df=pd.read_csv(raw[0]).drop(drop_columns, 1)
        for j in range(4,
                       #correct_used.shape[1]//2
                       5
                       ):
            plt.title(model_name[2])
            plt.plot(correct_used[:, j].cpu().detach(), label = df.columns[j]+"df")
            # plt.plot(result[:,j].cpu().detach(), label = df.columns[j]+"predict f")

            plt.plot(result[:,j].cpu().detach(), label = df.columns[j]+"predict f")
            plt.plot(result2[:,j].cpu().detach(), label = df.columns[j]+"predict g")
            plt.legend()
            plt.show()
