# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7bxCUtpGHCEwgT1_1m_lRL3c0rIo2t4
"""


import os
import torch
from pytorch_lightning.callbacks import EarlyStopping

import wandb
from torch import optim, nn, utils, Tensor
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
import pytorch_lightning as pl
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
from pytorch_lightning import loggers as pl_loggers
from pytorch_lightning.loggers import WandbLogger
import glob
from torch.optim import Optimizer
from torch.optim.lr_scheduler import ReduceLROnPlateau
from scipy.integrate import odeint


def z_derivatives(x, t, g,h,b, input):
    return [x[1]-input, -(1 / x[0]) * (x[1] ** 2 + b * x[1] + g * x[0] - g * h)]
def input_func(input,t, duration):
    return 0.25 * np.sin(2 * np.pi / duration * input* t)



def make_water_data(num_domains, num_points):

    g = np.random.normal(9.81, 1,num_domains)  # m/s^2
    h = np.random.normal(0.1, 0.01,num_domains) # m
    b = np.random.normal(0.25,0.025,num_domains)   # m/s
    input = np.random.normal(2,0.5, num_domains)   # m/s

    # g = np.ones(num_domains) *9.81 # m/s^2
    # h = np.ones(num_domains) *0.1  # m
    # b = np.ones(num_domains) *0.25  # m/s
    # input = np.ones(num_domains)*2


    #solve=time=numpoints+1

    start=0
    end=3
    duration=end-start
    time = np.arange(start, end, duration/(num_points+1))

    full=np.random.rand(num_domains, num_points+1, in_dim)
    # full[0, 0]=np.array([2e-3, 0])
    for i in range(num_domains):
        def gen_func(x, t):
            return z_derivatives(x, t, g[i], h[i], b[i], input_func(input[i],t,duration))

        temp= odeint(gen_func, full[i,0, :], time
                     ) #temp[:,0]=pos
        full[i]=temp[np.newaxis,:]

    x=full[:, :num_points]
    y=full[:,1:]
    #coef will be num_domain, 3
    #y will be num_domains, num_points, out_dim=1

    y=torch.Tensor(y)

    x=torch.Tensor(
        np.concatenate(
            (x,
             input_func(input.reshape((-1,1)),
                        time[:-1].reshape((1,-1)),
                        duration)[:, :,np.newaxis]), axis=-1))
    #y num_domain, num_points, in_dim, input num_domain, time num_points+1

    result=[]
    for i in range(num_domains):
        result.append(x[i:i+1, :, :])
        result.append(y[i:i+1, :, :])
    #[(num_points, in_dim), num_points(out_dim)]
    return result


class linear_relu(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim), nn.ReLU()])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))
            self.net.append(nn.ReLU())

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)
class linear_elu(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim), nn.ELU()])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))
            self.net.append(nn.ELU())

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)
class linear(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, depth):
        super().__init__()
        self.net = nn.ModuleList([nn.Linear(in_dim, hidden_dim)])
        for i in range(depth):
            self.net.append(nn.Linear(hidden_dim, hidden_dim))

        self.net.append(nn.Linear(hidden_dim, out_dim))
        self.net=nn.Sequential(*self.net)
    def forward(self, x):
        return self.net(x)






class TrainInvariant(pl.LightningModule):
    def __init__(self, in_dim, f_embed_dim,  g_embed_dim, out_dim, num_domains):
        super().__init__()
        self.invariant=nn.LSTM(in_dim, hidden_size=f_embed_dim, num_layers=2, proj_size=out_dim, batch_first=True)
        self.train_variants=nn.ModuleList([nn.LSTM(in_dim, hidden_size=g_embed_dim, num_layers=2, proj_size=out_dim,batch_first=True)for i in range (num_domains)])
        self.test_variant=nn.LSTM(in_dim, hidden_size=g_embed_dim, num_layers=2, proj_size=out_dim, batch_first=True)
        self.num_domains=num_domains
        self.eta=lambda x,y: x+y

        self.loss=nn.MSELoss()
    def forward(self, x, domain_num):
        result_f = self.invariant(x)
        result_g =self.train_variants[domain_num](x)

        return self.eta(result_f[0], result_g[0])

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        # it is independent of forward

        losses=[self.loss(self(batch[2*i], i), batch[2*i+1]) for i in range (self.num_domains)]
        loss=0
        for i in range(self.num_domains):
            loss+=losses[i]
        loss=loss/len(losses)
        self.log("train_loss", loss)
        return loss

    def validation_step(self, batch, batch_idx) :
        losses = [self.loss(self(batch[2*i], i), batch[2*i+1]) for i in range(self.num_domains)]

        loss = 0
        for i in range(self.num_domains):
            loss += losses[i]
        loss = loss / len(losses)        # Logging to TensorBoard (if installed) by default
        self.log("val_loss", loss)
    # def on_fit_end(self):

    def configure_optimizers(self):
        #check if all there
        optimizer = optim.Adam(self.parameters(), lr=1e-3)

        return optimizer



def get_latest_file():
    list_of_files = glob.glob(os.path.dirname(__file__) + '/DA Thesis/**/*.ckpt',
                              recursive=True)  # * means all if need specific format then *.csv
    latest_file = max(list_of_files, key=os.path.getctime)
    return latest_file
if __name__=="__main__":
    # define any number of nn.Modules (or use your current ones)


    in_dim = 2
    out_dim = 1
    np.random.seed(0)
    torch.use_deterministic_algorithms(True)
    torch.manual_seed(0)

    key="c20d41ecf28a9b0efa2c5acb361828d1319bc62e"
    num_domains=2


    val_coef = np.array([0.8, 0.1, .2])
    num_points = 2999
    f_embed_dim = 20
    g_embed_dim=10
    # f_layers=2
    # g_layers=2
    max_epoch=1600

    train_dataset = TensorDataset(*make_water_data(num_domains, num_points,))
    val_dataset = TensorDataset(*make_water_data(num_domains, num_points,))

    # train_dataset = TensorDataset(*make_quad_data_val(num_val_io_pairs, val_coef))
    # val_dataset = TensorDataset(*make_quad_data_val(num_points, val_coef))

    train_loader = DataLoader(train_dataset, batch_size=20, shuffle=True)
    val_loader = DataLoader(val_dataset,batch_size=20)
    # val_loader=train_loader
    tb_logger = pl_loggers.TensorBoardLogger(save_dir="lightning_logs/trash")
    wandb_logger=WandbLogger(project="DA Thesis", name="trash",log_model="True")
    wandb.init() ########################################################
    wandb_logger.experiment.config.update({
                                           "num_points": num_points,
                                           "num_domains": num_domains,
                                           "f_embed_dim":f_embed_dim,
                                           "g_embed_dim": g_embed_dim,
                                           "max_epoch": max_epoch,
                                           "file":os.path.basename(__file__)})

    base_trans=TrainInvariant(in_dim, f_embed_dim=f_embed_dim, g_embed_dim=g_embed_dim,out_dim=out_dim,num_domains=num_domains)


    # base_trans = TrainInvariant.load_from_checkpoint(get_latest_file(),in_dim, f_embed_dim=f_embed_dim,
    #                                                  g_embed_dim=g_embed_dim,
    #                                                  out_dim=out_dim,
    #                                                  num_domains=1)
    # base_trans = TrainInvariant.load_from_checkpoint("epoch=483-step=484.ckpt",
    #                                                 in_dim=in_dim,
    #                                                  f_embed_dim=f_embed_dim,
    #                                                  g_embed_dim=g_embed_dim,
    #                                                  out_dim=out_dim,
    #                                                  num_domains=num_domains)


    wandb_logger.watch(base_trans, log="all")

    early_stop_callback = EarlyStopping(monitor="val_loss", min_delta=0.0001, patience=200)
    # small_error_callback = EarlyStopping(monitor="val_loss", stopping_threshold=0.02)

    trainer1 = pl.Trainer(limit_train_batches=100,
                          logger=wandb_logger,
                          max_epochs=max_epoch,
                          # log_every_n_steps = 5,
                          accelerator="gpu", devices=1,
                          callbacks=[
                              early_stop_callback,
                                     # small_error_callback
                                     # model_checkpoint
                                     ],
                      # fast_dev_run=True
                      )
    # trainer2 = pl.Trainer(limit_train_batches=100,
    #                  logger=tb_logger,
    #                   max_epochs=2400,
    #                   log_every_n_steps = 1,
    # accelerator = "gpu", devices = 1,
    #
    # # fast_dev_run=True
    #
    #                   )


    #
    # idea_module

    # trainer1.fit(idea_module2, train_loader,val_loader)

    trainer1.fit(base_trans, train_loader, val_loader)

    wandb.save(get_latest_file())

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir /content/drive/MyDrive/Masters/Thesis/lightning_logs --port=8008
#
# val_dataset[6]
#
# train_dataset[0]
#
# idea_module2(val_dataset[0:1][0],val_dataset[0:1][2] )

# val_dataset[0:1][1]



# Commented out IPython magic to ensure Python compatibility.
# %debug

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7bxCUtpGHCEwgT1_1m_lRL3c0rIo2t4
"""